
<!-- Scripts -->
{!! Packer::js([
    '/azia/lib/jquery/jquery.min.js',
    '/azia/lib/bootstrap/js/bootstrap.bundle.min.js',
    'vendor/jsvalidation/js/jsvalidation.js',
    '/azia/lib/ionicons/ionicons.js',
    '/azia/lib/jquery.flot/jquery.flot.js',
    '/azia/lib/jquery.flot/jquery.flot.categories.js',
    '/azia/lib/jquery.flot/jquery.flot.resize.js',
    '/azia/lib/flot.curvedlines/curvedLines.js',
    '/azia/js/azia.js',

    '/azia/js/dashboard.sampledata.js',
    '/azia/js/chart.flot.sampledata.js',

    '/js/common.js',

    ],
    '/storage/cache/js/'
) !!}

// '/plugins/bootstrap-select/js/bootstrap-select.js',
// '/plugins/jquery-slimscroll/jquery.slimscroll.js',
// '/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js',
// '/plugins/node-waves/waves.js',
// '/plugins/bootstrap-notify/bootstrap-notify.js',
// '/plugins/jquery.number.min.js',
// '/plugins/jquery-datatable/jquery.dataTables.js',
// '/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js',
// '/plugins/jquery-datatable/extensions/responsive/js/dataTables.responsive.js',
// '/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js',
// '/plugins/jquery-datatable/extensions/export/buttons.html5.min.js',
// '/plugins/jquery-datatable/extensions/export/buttons.print.min.js',
// '/plugins/jquery-datatable/extensions/export/jszip.min.js',
// '/plugins/jquery-datatable/extensions/export/pdfmake.min.js',
// '/plugins/jquery-datatable/extensions/export/vfs_fonts.js',
// '/plugins/offlinejs/offline.min.js',
// '/plugins/select2-4.0.3/dist/js/select2.full.min.js',
// '/plugins/bootstrap-fileinput/js/fileinput.min.js',
// '/plugins/momentjs/moment.js',
// '/plugins/momentjs/locale/'.app()->getLocale().'.js',
// '/plugins/bootstrap-daterangepicker/daterangepicker.js',
// '/plugins/jquery-countto/jquery.countTo.js',
// '/plugins/bootstrap-datetimepicker/dist/js/bootstrap-datetimepicker.min.js',
// '/plugins/jquery-comments/js/jquery.textcomplete.min.js',
// '/plugins/jquery-comments/js/jquery-comments.min.js',
// '/plugins/jquert-query-builder/js/query-builder.standalone.js',
// '/plugins/js.cookie.js',
// '/js/BapConfig.js',
// '/js/BapDatatable.js',
// '/js/BapPlatform.js',
// '/plugins/jquery-datatable/yadcf/jquery.dataTables.yadcf.js',
// '/plugins/jquery-jscroll/jquery.jscroll.min.js',
// '/plugins/select-list-action/jquery.selectlistactions.js',
// '/plugins/bootstrap-tagsinput/typeahead.bundle.js',
// '/plugins/bootstrap-tagsinput/bootstrap-tagsinput.js',
// '/plugins/summernote/summernote.min.js',
// '/modules/notifications/js/BAP_Notifications.js'